<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad7010a0a757365722e70726f746f12047573657222190a0b5265717565" .
            "737455736572120a0a026964180120012805223d0a0455736572120a0a02" .
            "4944180220012805120c0a044e616d65180320012809120e0a064d6f6269" .
            "6c65180420012809120b0a0341676518052001280532610a0b5573657253" .
            "657276696365122e0a0b47657455736572496e666f12112e757365722e52" .
            "657175657374557365721a0a2e757365722e55736572220012220a064372" .
            "65617465120a2e757365722e557365721a0a2e757365722e557365722200" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

