<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>user.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ID = 2;</code>
     */
    private $ID = 0;
    /**
     * Generated from protobuf field <code>string Name = 3;</code>
     */
    private $Name = '';
    /**
     * Generated from protobuf field <code>string Mobile = 4;</code>
     */
    private $Mobile = '';
    /**
     * Generated from protobuf field <code>int32 Age = 5;</code>
     */
    private $Age = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $ID
     *     @type string $Name
     *     @type string $Mobile
     *     @type int $Age
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 ID = 2;</code>
     * @return int
     */
    public function getID()
    {
        return $this->ID;
    }

    /**
     * Generated from protobuf field <code>int32 ID = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setID($var)
    {
        GPBUtil::checkInt32($var);
        $this->ID = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Mobile = 4;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->Mobile;
    }

    /**
     * Generated from protobuf field <code>string Mobile = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->Mobile = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 Age = 5;</code>
     * @return int
     */
    public function getAge()
    {
        return $this->Age;
    }

    /**
     * Generated from protobuf field <code>int32 Age = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->Age = $var;

        return $this;
    }

}

